### ISSUE TITLE
CORS issue when trying to run the application from source code

### ISSUE THREAD

**Issue by parashar333** [arunbandari/mongo-gui#118]
![image](https://github.com/arunbandari/mongo-gui/assets/73868235/752e98d8-4c5f-429f-b46a-202555558f05)
Running fine when removed the auth middleware

**Comment by arunbandari** [comment]
@parashar333 does your commit fix this issue?

**Comment by parashar333** [comment]
> @parashar333 does your commit fix this issue?

Yes @arunbandari. It fixed the issue mentioned above.
