### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by 0416vidya** [arunbandari/mongo-gui#23]
Selectable formats:
* JSON
* CSV

**Comment by SteveFirsake** [comment]
It does CSV exporting for a collection based on a filter (key:value) ?

This would make it the Greatest of all Time :)

@arunbandari, does it?

**Comment by arunbandari** [comment]
Yes @SteveFirsake, we can apply a filter then export 👍

**Comment by SteveFirsake** [comment]
@arunbandari is there a specific button to:

1. export to CSV?
2. export at all? I only see a copy icon on hovering the mouse pointer.

Where in the tool can one find the button?

**Comment by arunbandari** [comment]
>Yes @SteveFirsake, we can apply a filter then export 👍

Sorry for the confusion @SteveFirsake, this story is in progress (under development) and the idea is this **we can apply a filter then export**

**Comment by SteveFirsake** [comment]
Ok
