### ISSUE TITLE
Make URL limit customizable

### ISSUE THREAD

**Issue by ManuConstantin** [arunbandari/mongo-gui#30]
_If you try modifying a large JSON this will happen unless you do something like app.use(express.bodyParser({limit: '100mb'}));
If would be nice to have this as a env parameter._

> { PayloadTooLargeError: request entity too large
>     at readStream (/usr/local/lib/node_modules/mongo-gui/node_modules/raw-body/index.js:155:17)
>     at getRawBody (/usr/local/lib/node_modules/mongo-gui/node_modules/raw-body/index.js:108:12)
>     at read (/usr/local/lib/node_modules/mongo-gui/node_modules/body-parser/lib/read.js:77:3)
>     at jsonParser (/usr/local/lib/node_modules/mongo-gui/node_modules/body-parser/lib/types/json.js:135:5)
>     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:317:13)
>     at /usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:335:12)
>     at next (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:275:10)
>     at urlencodedParser (/usr/local/lib/node_modules/mongo-gui/node_modules/body-parser/lib/types/urlencoded.js:100:7)
>   message: 'request entity too large',
>   expected: 284167,
>   length: 284167,
>   limit: 102400,
>   type: 'entity.too.large' }
> { PayloadTooLargeError: request entity too large
>     at readStream (/usr/local/lib/node_modules/mongo-gui/node_modules/raw-body/index.js:155:17)
>     at getRawBody (/usr/local/lib/node_modules/mongo-gui/node_modules/raw-body/index.js:108:12)
>     at read (/usr/local/lib/node_modules/mongo-gui/node_modules/body-parser/lib/read.js:77:3)
>     at jsonParser (/usr/local/lib/node_modules/mongo-gui/node_modules/body-parser/lib/types/json.js:135:5)
>     at Layer.handle [as handle_request] (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:317:13)
>     at /usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:335:12)
>     at next (/usr/local/lib/node_modules/mongo-gui/node_modules/express/lib/router/index.js:275:10)
>     at urlencodedParser (/usr/local/lib/node_modules/mongo-gui/node_modules/body-parser/lib/types/urlencoded.js:100:7)

**Comment by arunbandari** [comment]
Thank you for the suggestion @ManuConstantin

**Comment by arunbandari** [comment]
@ManuConstantin You can now use the env variable **BODY_SIZE** to set the max body size and also the default limit is increased to 50mb from 2mb.
