### ISSUE TITLE
Mongo Eroor when I install the project

### ISSUE THREAD

**Issue by FoudreNoire26i** [arunbandari/mongo-gui#60]
Hello, when I cloned the project, I tried to use it.I did my "npm install", but when i want to start the application I have the following error. Can anyone help me ?
Thanks

<img width="1141" alt="Capture d’écran 2021-06-28 à 09 52 58" src="https://user-images.githubusercontent.com/63561849/123600097-9fed7c80-d7f6-11eb-9247-85c1fa9bddd5.png">

**Comment by arunbandari** [comment]
@FoudreNoire26i Have you started mongodb server? mongo-gui doesn't automatically start mongodb server

**Comment by 0416vidya** [comment]
@FoudreNoire26i Closing this. Please reopen it if you still face the issue after starting the Mongo Server.
