### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ralcorta** [arunbandari/mongo-gui#68]
Hi, I'm creating a docker-compose.yml file but when I use the compose configuration from the doc, I have this error message:

> mongo-gui_1        | [Error: ENOENT: no such file or directory, stat '/app../public/index.html'] {
mongo-gui_1        |   errno: -2,
mongo-gui_1        |   code: 'ENOENT',
mongo-gui_1        |   syscall: 'stat',
mongo-gui_1        |   path: '/app../public/index.html',
mongo-gui_1        |   expose: false,
mongo-gui_1        |   statusCode: 404,
mongo-gui_1        |   status: 404
mongo-gui_1        | }

What's going on? What can I do to fix it?

**Comment by josephlim75** [comment]
It seems like there is a bug in `server.js` in this line `app.get('/', (req, res) => res.sendFile(__dirname + '../public/index.html'));`.  This has been fixed in the latest commit but I believe it hasn't build the latest docker image

**Comment by josephlim75** [comment]
I'm going to rebuild the docker image myself with the latest code to see if it fixed

**Comment by josephlim75** [comment]
After rebuilding the docker image with the latest commit, it works :)

![image](https://user-images.githubusercontent.com/21043283/130176551-140c047b-9494-4efa-bc3d-a41e4531a5c4.png)

**Comment by AndrewMarchukov** [comment]
not fixed, where new images on dockerhub?
