### ISSUE TITLE
Simple Authentication Feature

### ISSUE THREAD

**Issue by josephlim75** [arunbandari/mongo-gui#69]
Any plan to add simple authentication feature into this gui ?

**Comment by ugleiton** [comment]
But as a workaround you can protect the application behind an nginx proxy with authentication, I've done this in other projects and it worked, this does not replace a native authentication that would be the best option.
See an example at http://shairosenfeld.blogspot.com/2011/03/authorization-header-in-nginx-for.html

**Comment by josephlim75** [comment]
I'm closing this issue.  Thanks
