### ISSUE TITLE
MongoError: can't get regex from filter doc

### ISSUE THREAD

**Issue by warren-bank** [arunbandari/mongo-gui#87]
Hi. Great project!

I just signed up for a [mongodb.com free tier account](https://www.mongodb.com/pricing).
I installed your server and tried to connect to this DB, but nothing was working.. and it was displaying error messages.

The network tab showed that this request:
```
  http://localhost/databases?includeCollections=true
```
was returning:
```
  400 Bad Request
  MongoError: can't get regex from filter doc Error parsing value [{$not [{$regex {"pattern": "system.+$", "options": ""}}]}] to RegEx: Must specify $regex field
```

This regex pattern is used in two places:
1. [listing databases with all associated collections](https://github.com/arunbandari/mongo-gui/blob/v0.0.17/src/controllers/common.js#L10)
2. [listing collections for a single database](https://github.com/arunbandari/mongo-gui/blob/v0.0.17/src/controllers/common.js#L51)

In both cases, I replaced:
```
  .listCollections({ name: { $not: { $regex: /system.+$/ } } }).toArray()
```
with:
```
  .listCollections().toArray()
```
..and now the server works properly.

I don't know if this cloud service  is a special case.. but I just wanted to make a PSA about this issue.
Would it be worth considering a cli option to prevent using this regex filter?
ex: `mongo-gui --all-collections -p 80 -u ...`

**Comment by warren-bank** [comment]
Windows 7 SP1
node v16.14.0
mongodb v5.0.6

**Comment by vidyasagar-m** [comment]
fixed.
