### ISSUE TITLE
Feature request: Built in basic auth

### ISSUE THREAD

**Issue by jashson** [arunbandari/mongo-gui#95]
It would be great to have a built in basic auth like mongo-express has.

**Comment by szbk** [comment]
I needed this too. I opened a PR 😊 This feature is now available 👊🏻

**Added simple authorization for secure login**
[https://github.com/arunbandari/mongo-gui/pull/112](url)

**Comment by arunbandari** [comment]
> I opened a PR 😊 This feature is now available 👊🏻

So closing this.
